server:
  port: 38000
  servlet:
    context-path: /openai-api

spring:
  application:
    name: rubber-at-tennis-openai
  profiles:
    active: master
  jackson:
    date-format:  "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+08:00"
    default-property-inclusion: non_empty
